default_install_hook_types:
  - pre-commit
  - pre-push
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=5120]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm run black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: pdm run mypy
        language: system
        types: [python]
        files: '^(scripts/|src/|tests/)'
      - id: pytest-check
        name: pytest-check
        entry: pdm run pytest
        language: system
        types: [python]
        pass_filenames: false
      - id: commitizen
        name: commitizen
        entry: pdm run cz check
        language: system
        types: [python]
        args: [--rev-range, origin/main..HEAD]
        stages: [push]
        pass_filenames: false
